// components/layout/Footer/Footer.vue
<template>
  <footer>
    Made with ❤️ by
    <span>&nbsp;Jules P.</span>
  </footer>
</template>

<style scoped>
footer {
  font-size: 0.8rem;
  font-style: italic;
  font-weight: 300;
  text-align: center;
  margin-top: 3rem;
  margin-bottom: 1rem;
}

span {
  font-weight: 500;
  color: transparent;
  background-image: linear-gradient(to right, var(--blue), var(--purple));
  background-clip: text;
}

</style>

// app/(layout)/footer.tsx
import React from "react";

const Footer = () => {
  return (
    <footer className={"italic font-light text-center my-3"}>
      Made with <span className={"text-red-500"}>❤</span> by{" "}
      <span
        className={
          "font-normal bg-clip-text text-transparent bg-gradient-to-r from-purple-500 to-blue-500"
        }
      >
        Jules
      </span>
    </footer>
  );
};

export default Footer;
