// app/projects/[slug].tsx
import { getAllProjects, getProjectBySlug } from "../../lib/api";
import Rainbow from "../../styles/rainbow";
import { ProjectType } from "../../interface/ProjectType";
import markdownToHtml from "../../lib/markdownToHtml";
import PillList from "../../components/Pills/pillList";
import { FC } from "react";
import { MDXRemote } from "next-mdx-remote";
import styled from "styled-components";
import Image from "next/image";

const Img = styled.div`
  flex-basis: 200px;
  width: 100%;
  position: relative;
`;

const ProjectContainer = styled.article`
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: flex-start;
  margin: 0 auto;
  height: 100%;
  max-width: 750px;
  gap: 1rem;
  padding: 1rem 1rem;

  & p {
    font-size: 1.2rem;
    line-height: 1.5;
    letter-spacing: -0.01em;
    margin-block-end: 0.5rem;
  }

  & h1 {
    font-size: 2rem;
    line-height: 1.2;
    letter-spacing: -0.01em;
    font-weight: 700;
  }

  & blockquote > p {
    font-size: 1.1rem;
    line-height: 1.5;
    font-weight: 400;
    border-left: 2px solid ${({ theme }) => theme.primary};
    padding: 0.5rem 0.5rem 0.5rem 1rem;
    background: ${({ theme }) => theme.dark};
  }

  & code {
    color: ${({ theme }) => theme.primary};
    background: ${({ theme }) => theme.light};
    padding: 2px 5px;
    border-radius: 5px;
  }
`;

const ProjectTitle = styled.h1`
  flex: 1;
  letter-spacing: 2px;
  font-weight: 700;
`;

const Project: FC<{ project: ProjectType }> = ({ project }) => {
  return (
    <ProjectContainer>
      <ProjectTitle>{project.title}</ProjectTitle>
      <Img>
        <Image src={project.coverImage} alt={project.title} fill={true} />
      </Img>
      <PillList pills={project.tags} />
      <MDXRemote {...(project.content as any)} components={{ Rainbow }} />
    </ProjectContainer>
  );
};

export default Project;

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const project = getProjectBySlug(params.slug, [
    "title",
    "date",
    "slug",
    "author",
    "content",
    "ogImage",
    "coverImage",
    "tags",
  ]);
  const content = await markdownToHtml(project.content || "");

  return {
    props: {
      project: {
        ...project,
        content,
      },
    },
  };
}

export async function getStaticPaths() {
  const projects = getAllProjects(["slug"]);

  return {
    paths: projects.map((project) => {
      return {
        params: {
          slug: project.slug,
        },
      };
    }),
    fallback: false,
  };
}

// pages/projects/[slug].vue
<script setup>
const route = useRoute();
const project = useAsyncData("projects", () =>
  queryContent("projects").where({ _path: route.path }).findOne(),
).data;
</script>

<template>
  <section>
    <h2>{{ project.title }}</h2>
    <article>
      <img :src="project.coverImage" :alt="project.title" />
      <ContentRenderer tag="article" :value="project">
        <template #empty>
          <div class="skeleton-title"></div>
          <div class="skeleton-text"></div>
          <div class="skeleton-title"></div>
          <div class="skeleton-text"></div>
          <div class="skeleton-title"></div>
          <div class="skeleton-text"></div>
        </template>
      </ContentRenderer>
    </article>
  </section>
</template>

<style scoped>
h2 {
  font-size: 3rem;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.05rem;
  margin-bottom: 1rem;
}

section {
  max-width: 876px;
  margin: 0 auto;
}

article {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: 1rem;
}

img {
  flex: 1;
  position: relative;
  height: 300px;
  object-fit: cover;
}

.skeleton-title {
  width: 16ch;
  height: 1em;
  font-size: 2em;
  margin: 0.67em 0;
  background: #383838;
  border-radius: 1em;
  position: relative;
  overflow: hidden;

  &::after {
    content: "";
    position: absolute;
    inset: 0;
    background-image: linear-gradient(
      90deg,
      rgba(255, 255, 255, 0) 0,
      rgba(255, 255, 255, 0.5) 50%,
      rgba(255, 255, 255, 0) 100%
    );
    animation: shimmer 1s infinite;
  }
}

.skeleton-text {
  width: 100%;
  height: 4em;
  background: #383838;
  border-radius: 1em;
  position: relative;
  overflow: hidden;

  &::after {
    content: "";
    position: absolute;
    inset: 0;
    background-image: linear-gradient(
      90deg,
      rgba(255, 255, 255, 0) 0,
      rgba(255, 255, 255, 0.5) 50%,
      rgba(255, 255, 255, 0) 100%
    );
    animation: shimmer 1s ease-in-out infinite;
  }
}

@keyframes shimmer {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(100%);
  }
}
</style>
