// src/app/projects/[slug]/page.tsx
import React from "react";
import { getAllProjects, getProjectBySlug } from "../projectsConnector";
import Image from "next/image";
import Content from "./content";
import { serialize } from "next-mdx-remote/serialize";

export function generateStaticParams() {
  const projects = getAllProjects(["slug"]);
  return projects.map((project) => ({
    slug: project.slug,
  }));
}

const Page = async ({ params }: { params: any }) => {
  const project = getProjectBySlug(params.slug, [
    "title",
    "content",
    "coverImage",
  ]);
  return (
    <>
      <h1 className={"text-5xl mb-5"}>{project.title}</h1>
      <section className={"flex flex-wrap justify-between gap-3"}>
        <div className={"w-[700px] flex-shrink"}>
          <Content content={await serialize(project.content)} />
        </div>
        <div className={"relative flex-1 h-64"}>
          <Image
            src={project.coverImage}
            alt={project.title}
            fill={true}
            style={{ objectFit: "cover", objectPosition: "bottom" }}
          />
        </div>
      </section>
    </>
  );
};

export default Page;

// pages/projects/[slug].vue
<script setup>
const route = useRoute();
const project = useAsyncData("projects", () => queryContent("projects").where({ _path: route.path }).findOne()).data;

</script>

<template>
  <div><h2>{{ project.title }}</h2>
    <section>
      <img
        :src="project.coverImage"
        :alt="project.title"
      />
      <ContentRenderer :value="project" />
    </section>
  </div>
</template>

<style scoped>
h2 {
  font-size: 3rem;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.05rem;
  margin-bottom: 1rem;
}

section {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: 1rem;
}

.content {
  flex: 1 1 100%;
  max-width: 100%;
}

img {
  flex: 1;
  position: relative;
  height: 300px;
  object-fit: cover;
}

</style>
