// components/layout/Footer/Footer.vue
<template>
  <footer>
    Made with ❤️ by
    <span>&nbsp;Jules P.</span>
  </footer>
</template>

<style scoped>
footer {
  font-size: 0.8rem;
  font-style: italic;
  font-weight: 300;
  text-align: center;
  margin-top: 3rem;
  margin-bottom: 1rem;
}

span {
  font-weight: 500;
  color: transparent;
  background-image: linear-gradient(to right, var(--blue), var(--purple));
  background-clip: text;
}

</style>

// components/Layout/Footer/footer.tsx
import styled from "styled-components";

const FooterWrap = styled.footer`
  margin: 2rem 0;
  padding: 2rem;
  text-align: center;
  font-size: 0.8rem;
  font-weight: 300;
  color: ${({ theme }) => theme.lightest};
  letter-spacing: -0.5px;
`;

const Footer = () => (
  <FooterWrap>
    Made with <span>❤️</span> by Jules.
  </FooterWrap>
);

export default Footer;
