// components/project/Pill.vue
<script setup>
const { color, rank } = defineProps({
  color: {
    type: String,
    required: true
  },
  rank: {
    type: Number,
    required: true
  }
});

const computedStyle = computed(() => {
  return {
    "--pill-color": color,
    "--rank": rank
  };
});
</script>

<template>
  <li :style="computedStyle">
    <slot />
  </li>
</template>

<style scoped>
li {
  display: inline-block;
  position: relative;
  padding: 0.25rem 0.75rem;
  font-size: 0.75rem;
  font-weight: 300;
  white-space: nowrap;
  letter-spacing: 0.05rem;
  background-color: var(--primary-background-color);
  border-radius: 0.75rem;
  overflow: clip;
  overflow-clip-margin: var(--clip-margin);
  --clip-margin: 2px;
  --pill-color: var(--primary-action);
  --rank: 1;
}

li::before {
  z-index: -1;
  position: absolute;
  top: 50%;
  left: 50%;
  width: calc(100% + 0.5rem);
  aspect-ratio: 1/1;
  transform: translate(-50%, -50%);
  content: "";
  /*rainbow conic gradient*/
  background: conic-gradient(
    var(--pill-color),
    var(--text-color),
    var(--pill-color)
  );
  animation-duration: 5s;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  animation-name: rotation;
  animation-delay: calc(var(--rank) * 1s);
}

@keyframes rotation {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}

</style>

// components/Pills/Pill/pill.tsx
import React, { FC, ReactNode } from "react";
import styled from "styled-components";

export const PillRoot = styled.li<{ color: string | undefined, rank: number }>`
  position: relative;
  display: inline-block;
  padding: 0.5rem 1rem;
  border-radius: 1rem;
  border: 1px solid ${({ theme, color }) => color || theme.lightest};
  color: ${({ theme, color }) => color || theme.lightest};
  font-size: 0.8rem;
  font-weight: 500;
  letter-spacing: -0.5px;
  transition: 0.3s ease-in-out;
  overflow: hidden;

  &::before {
    z-index: -1;
    content: "";
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: inherit;
    top: 0;
    left: -100%;
    background-image: linear-gradient(${({ theme, color }) => color || theme.lightest},
    ${({ theme, color }) => color || theme.lightest});
    transition: left 0.3s ease-in-out;
    transition-delay: ${({ rank }) => rank * 50}ms;
  }
`;

const Pill: FC<{ children: ReactNode; color: string; rank: number }> = ({
                                                                          children,
                                                                          color,
                                                                          rank
                                                                        }) => {
  return <PillRoot rank={rank} color={color}>{children}</PillRoot>;
};

export default Pill;
