// components/Card/card.tsx
import styled from "styled-components";
import React, { FC, ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import PillList from "../Pills/pillList";

export const CardContainer = styled.a`
  display: flex;
  flex: 1 1 300px;
  flex-direction: column;
  justify-content: space-between;
  align-items: flex-start;
  gap: 1rem;
  height: 350px;
  margin: 2rem 0;
  padding: 1rem 1rem;
  transform: rotate(0.4deg);
  transition: transform 0.3s ease-in-out;
  cursor: pointer;
  opacity: 0.9;

  &:hover {
    transform: rotate(-0.4deg);
    opacity: 1;
    
 & ul > li {
    color: ${({ theme }) => theme.dark};
    border: 1px solid ${({ theme }) => theme.dark};
    &::before {
      left: 0;
    }
  }
`;
const Img = styled.div`
  flex: 0 0 60%;
  width: 100%;
  position: relative;
  object-fit: cover;
`;
export const Card: FC<{
  children: ReactNode;
  title: string;
  src: string;
  alt: string;
  href: string;
  pills: any[];
}> = ({ children, title, src, alt, href, pills }) => {
  return (
    <Link href={href} passHref>
      <CardContainer>
        <Img>
          <Image
            src={src}
            alt={alt}
            fill={true}
            style={{ objectFit: "cover", objectPosition: "bottom" }}
          />
        </Img>
        <h3>{title}</h3>
        <p>{children}</p>
        <PillList pills={pills} />
      </CardContainer>
    </Link>
  );
};

// components/project/Card.vue
<script setup>
const { project } = defineProps({
  project: {
    type: Object,
    required: true
  }
});

</script>

<template>
  <nuxt-link :href="'project/'+ project.slug">
    <div>
      <img
        :src="project.coverImage"
        :alt="project.alt"
      />
    </div>
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
    <ul>
      <ProjectPill v-for="tag in project.tags" :key="tag" :rank="1" :color="tag[1]">
        {{ tag[0] }}
      </ProjectPill>
    </ul>
  </nuxt-link>
</template>

<style scoped>
a {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  margin: 0.5rem;
  padding: 1rem;
  gap: 1rem;
  isolation: isolate;
  border: 1px solid transparent;
  border-radius: 0.375rem;
  transition: border 300ms ease-in-out;
}

a:hover {
  border: 1px solid var(--text-color);
}

img {
  flex-shrink: 0;
  position: relative;
  width: 100%;
  height: 180px;
  object-fit: cover;

}

h3 {
  font-size: 1.2rem;
  font-weight: 600;
}

p {
  font-size: 1rem;
  font-weight: 400;
  line-clamp: 3;
  overflow: hidden;
  text-overflow: ellipsis;
}

ul {
  display: flex;
  gap: 0.5rem;
}

</style>
