// pages/project/[slug].vue
<script setup>

const getBySlug = (slug) => {
  return [{
    title: "Project 1",
    slug: "project-1",
    date: "2021-01-01",
    excerpt: "This is the excerpt for Project 1.",
    coverImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    alt: "Project 1",
    tags: [["tag1", "red"], ["tag2", "blue"]]
  }].filter((project) => project.slug === slug)[0];
};
const route = useRoute();
const project = getBySlug(route.params.slug);
</script>

<template>
  <h2>{{ project.title }}</h2>
  <section>
    <div>
      <!--      <Content content={await serialize(project.content)} />-->
    </div>
    <img
      :src="project.coverImage"
      :alt="project.title"
    />
  </section>
</template>

<style scoped>
h2 {
  font-size: 3rem;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.05rem;
  margin-bottom: 1rem;
}

section {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: 1rem;
}

.content {
  flex: 1 1 100%;
  max-width: 100%;
}

img {
  flex: 1;
  position: relative;
  height: 300px;
  object-fit: cover;
}

</style>

// app/projects/[slug].tsx
import { getAllProjects, getProjectBySlug } from "../../lib/api";
import Rainbow from "../../styles/rainbow";
import { ProjectType } from "../../interface/ProjectType";
import markdownToHtml from "../../lib/markdownToHtml";
import PillList from "../../components/Pills/pillList";
import { FC } from "react";
import { MDXRemote } from "next-mdx-remote";
import styled from "styled-components";
import Image from "next/image";

const Img = styled.div`
  flex-basis: 200px;
  width: 100%;
  position: relative;
`;

const ProjectContainer = styled.article`
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: flex-start;
  margin: 0 auto;
  height: 100%;
  max-width: 750px;
  gap: 1rem;
  padding: 1rem 1rem;

  & p {
    font-size: 1.2rem;
    line-height: 1.5;
    letter-spacing: -0.01em;
    margin-block-end: 0.5rem;
  }

  & h1 {
    font-size: 2rem;
    line-height: 1.2;
    letter-spacing: -0.01em;
    font-weight: 700;
  }

  & blockquote > p {
    font-size: 1.1rem;
    line-height: 1.5;
    font-weight: 400;
    border-left: 2px solid ${({ theme }) => theme.primary};
    padding: 0.5rem 0.5rem 0.5rem 1rem;
    background: ${({ theme }) => theme.dark};
  }

  & code {
    color: ${({ theme }) => theme.primary};
    background: ${({ theme }) => theme.light};
    padding: 2px 5px;
    border-radius: 5px;
  }
`;

const ProjectTitle = styled.h1`
  flex: 1;
  letter-spacing: 2px;
  font-weight: 700;
`;

const Project: FC<{ project: ProjectType }> = ({ project }) => {
  return (
    <ProjectContainer>
      <ProjectTitle>{project.title}</ProjectTitle>
      <Img>
        <Image src={project.coverImage} alt={project.title} fill={true} />
      </Img>
      <PillList pills={project.tags} />
      <MDXRemote {...(project.content as any)} components={{ Rainbow }} />
    </ProjectContainer>
  );
};

export default Project;

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const project = getProjectBySlug(params.slug, [
    "title",
    "date",
    "slug",
    "author",
    "content",
    "ogImage",
    "coverImage",
    "tags",
  ]);
  const content = await markdownToHtml(project.content || "");

  return {
    props: {
      project: {
        ...project,
        content,
      },
    },
  };
}

export async function getStaticPaths() {
  const projects = getAllProjects(["slug"]);

  return {
    paths: projects.map((project) => {
      return {
        params: {
          slug: project.slug,
        },
      };
    }),
    fallback: false,
  };
}
